
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int TIMES = 8;
  public static final int AND = 23;
  public static final int NE = 22;
  public static final int LT = 20;
  public static final int IDENT = 30;
  public static final int SEMICOLON = 7;
  public static final int ELSE = 15;
  public static final int PLUS = 2;
  public static final int OR = 24;
  public static final int RPAREN = 5;
  public static final int INT = 10;
  public static final int NOT = 25;
  public static final int RCURLY = 12;
  public static final int RETURN = 6;
  public static final int INTCONST = 29;
  public static final int IF = 14;
  public static final int GT = 19;
  public static final int LPAREN = 4;
  public static final int RANDOMINT = 26;
  public static final int LE = 18;
  public static final int LCURLY = 11;
  public static final int COMMA = 27;
  public static final int EOF = 0;
  public static final int MAIN = 28;
  public static final int GE = 17;
  public static final int MINUS = 3;
  public static final int PRINT = 16;
  public static final int error = 1;
  public static final int EQ = 21;
  public static final int ASSIGN = 13;
  public static final int UMINUS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "LPAREN",
  "RPAREN",
  "RETURN",
  "SEMICOLON",
  "TIMES",
  "UMINUS",
  "INT",
  "LCURLY",
  "RCURLY",
  "ASSIGN",
  "IF",
  "ELSE",
  "PRINT",
  "GE",
  "LE",
  "GT",
  "LT",
  "EQ",
  "NE",
  "AND",
  "OR",
  "NOT",
  "RANDOMINT",
  "COMMA",
  "MAIN",
  "INTCONST",
  "IDENT"
  };
}

